### ISSUE TITLE
support for swrl buillt-in atoms

### ISSUE THREAD

**Issue by IbrahimMohammed47** [ignazio1977/hermit-reasoner#7]
Hello there, I'm using SWRL API v2.0.8 to author and manage rules to an ontology, At the same time, i'm using Hermit reasoner v1.3.8.413 to extract entities from the ontology. My problem is I get the following exception whenever i pass an ontology that contains swrl atoms to the createReasoner method, if there are no swrl constructs in the owl file, it would work like a charm. Is there any way to bypass that exception? 

    Exception in thread "main" java.lang.IllegalArgumentException: A SWRL rule uses a built-in atom, but built-in atoms are not supported yet.
        at org.semanticweb.HermiT.structural.OWLNormalization$RuleNormalizer.visit(OWLNormalization.java:1358)
        at uk.ac.manchester.cs.owl.owlapi.SWRLBuiltInAtomImpl.accept(SWRLBuiltInAtomImpl.java:96)
        at org.semanticweb.HermiT.structural.OWLNormalization$RuleNormalizer.visit(OWLNormalization.java:1247)
        at org.semanticweb.HermiT.structural.OWLNormalization.processAxioms(OWLNormalization.java:185)
        at org.semanticweb.HermiT.structural.OWLNormalization.processOntology(OWLNormalization.java:167)
        at org.semanticweb.HermiT.structural.OWLClausification.preprocessAndClausify(OWLClausification.java:153)
        at org.semanticweb.HermiT.Reasoner.loadOntology(Reasoner.java:208)
        at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:199)
        at org.semanticweb.HermiT.Reasoner.<init>(Reasoner.java:173)
        at org.semanticweb.HermiT.ReasonerFactory.createHermiTOWLReasoner(ReasonerFactory.java:51)
        at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:19)
        at org.semanticweb.HermiT.ReasonerFactory.createReasoner(ReasonerFactory.java:15)
        at com.guc.met.App.main(App.java:32)
`

**Comment by ignazio1977** [comment]
Is the ontology being modified while HermiT is using it? If not, I would create a new ontology and skip the swrl rules to feed to the reasoner.

**Comment by IbrahimMohammed47** [comment]
That's a good idea, could you tell me how to copy the current ontology to a new owl file without copying the rules? Can i do this programatically?

**Comment by ignazio1977** [comment]
Yes it can be done programmatically, I wouldn't save the ontology to disk though.

        List<SWRLRule> list= ontology.axioms(AxiomType.SWRL_RULE).collect(Collectors.toList());
        ontology.remove(list);
        OWLReasoner reasoner = ReasonerFactory.createReasoner(ontology);

**Comment by IbrahimMohammed47** [comment]
Great, I'll use this method then.
Thank you so much for your help :D .
